### ISSUE TITLE
Media added in Diskhook doesn't show up in the scheduled message

### ISSUE THREAD

**Issue by batmanscode** [Azim/ZimmyScheduler#1]
Great bot! Been trying out many but this one seems to work best :D

I tried adding an image under the "Files" section in Diskhook; it shows up in the preview but when the message gets scheduled and sent, only the text is there

Note that sending directly from Diskhook works as expected

**Comment by Azim** [comment]
Thank you, i will look into it. For now, i suggest uploading your images to image hosting of your choice (imgur or some private channel in discord would do) and attaching via the url instead

**Comment by Azim** [comment]
Seems to be the issue with how discohook handles sharing messages (aka its not on my end). 
I'll let the guys at discohook know.

**Comment by batmanscode** [comment]
Thank you @Azim, that sounds like a good option. I didn't know links from a private channel would render an image

Hmm I see. Maybe it's with their link generation? Since it works when entering the webhook URL and sending directly

**Comment by batmanscode** [comment]
It seems that rendering links don't work as expected but that's probably an issue with Diskhook

**Comment by Azim** [comment]
> It seems that rendering links don't work as expected but that's probably an issue with Diskhook

it probably depends on Discord actually. I know it worked for me most of the times, but in the end i decided on imgur as a most reliable option

**Comment by Azim** [comment]
> Hmm I see. Maybe it's with their link generation? Since it works when entering the webhook URL and sending directly

from what i see, the issue is that images you upload to discohook are only stored in your browser, until you hit "send", where it sends them to discord directly. With the way discohook currently works, it seems like it is impossible to share such uploaded files properly, but it will most likely be fixed after discohook's rewrite

**Comment by batmanscode** [comment]
> > Hmm I see. Maybe it's with their link generation? Since it works when entering the webhook URL and sending directly
> 
> from what i see, the issue is that images you upload to discohook are only stored in your browser, until you hit "send", where it sends them to discord directly. With the way discohook currently works, it seems like it is impossible to share such uploaded files properly, but it will most likely be fixed after discohook's rewrite

This makes sense. Looking forward to their rewrite then. Thanks

**Comment by batmanscode** [comment]
> > It seems that rendering links don't work as expected but that's probably an issue with Diskhook
> 
> it probably depends on Discord actually. I know it worked for me most of the times, but in the end i decided on imgur as a most reliable option

Tried both, didn't work :(

And fwiw neither discord links nor imgur links appear in the preview on Diskhook either

**Comment by Azim** [comment]
> Tried both, didn't work :(
> 
> And fwiw neither discord links nor imgur links appear in the preview on Diskhook either

Are you sure you're using the image link and not message link when trying discord's channel?

for imgur, you need to send a image url, instead of page url (https://imgur.com/cdSTl7l -> https://imgur.com/cdSTl7l.png)

**Comment by batmanscode** [comment]
> > Tried both, didn't work :(
> > And fwiw neither discord links nor imgur links appear in the preview on Diskhook either
> 
> Are you sure you're using the image link and not message link when trying discord's channel?
> 
> for imgur, you need to send a image url, instead of page url (https://imgur.com/cdSTl7l -> https://imgur.com/cdSTl7l.png)

For discord I used the message link and for imgur I used the direct link as you mentioned. Although I tried with a `.mp4`
